env:
  browser: true
  es2021: true
extends:
  - plugin:vue/vue3-recommended
  - standard-with-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - '@vue/eslint-config-prettier'
overrides: []
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
  sourceType: module
  createDefaultProgram: true
  project:
    - ./tsconfig.app.json
    - ./tsconfig.node.json
plugins:
  - vue
  - tsdoc
rules:
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/triple-slash-reference': off
  import/default: off
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
    vue-eslint-parser:
      - .vue
  import/resolver:
    typescript: {}
    alias:
      map:
        - ['@', './src']
        - ['~', './node_modules']
        - ['vue-markdown-wasm', './src']
      extensions:
        - .js
        - .ts
        - .jsx
        - .tsx
        - .vue
  vite:
    configPath: ./vite.config.ts
